How to handle this exception?